### ISSUE TITLE
Port information for some nodes cannot be extracted

### ISSUE THREAD

**Issue by qqilihq** [NodePit/knime-json-node-doc-generator#17]
For the following nodes we currently get the error “Could not create NodeModel”. Investigate reasons and fixes. 

- [x] `org.knime.base.node.io.filehandling.linereader.LineReaderNodeFactory`
- [x] `org.knime.base.node.preproc.append.row.AppendedRowsNodeFactory`
- [x] `org.knime.ext.mdf.base.nodes.reader.MdfReaderNodeFactory`
- [x] `org.knime.ext.poi2.node.read4.XLSReaderNodeFactory`
- [x] `org.knime.ext.poi2.node.write3.XLSAppenderNodeFactory`
- [x] `org.knime.ext.poi2.node.write3.XLSWriter2NodeFactory`
- [x] `org.knime.ext.powerbi.base.nodes.send.SendToPowerBINodeFactory`
- [x] `org.uni_leipzig.biggr.nodes.executor.FlinkExecutorNodeFactory`
- [x] `ws.palladian.nodes.retrieval.ip.FreeGeoIpNodeFactory`

**Comment by qqilihq** [comment]
Checked new `org.knime.ext.powerbi.base.nodes.send.SendToPowerBINodeFactory`

Actual error message:

```
WARN 	 main JsonNodeDocuGenerator	 Could not create NodeModel for org.knime.ext.powerbi.base.nodes.send.SendToPowerBINodeFactory
java.lang.UnsupportedOperationException: Method invocation not supported by ConfigurableNodeFactory
	at org.knime.core.node.ConfigurableNodeFactory.createNodeModel(ConfigurableNodeFactory.java:84)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.createNodeModel(JsonNodeDocuGenerator.java:494)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.generate(JsonNodeDocuGenerator.java:426)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.generate(JsonNodeDocuGenerator.java:468)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.generate(JsonNodeDocuGenerator.java:468)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.generate(JsonNodeDocuGenerator.java:468)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.generate(JsonNodeDocuGenerator.java:243)
	at de.philippkatz.knime.jsondocgen.JsonNodeDocuGenerator.start(JsonNodeDocuGenerator.java:198)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

`ConfigurableNodeFactory` is new with 4.1 and throws exception when calling `createNodeModel`.

The following nodes also inherit from `ConfigurableNodeFactory `:

- `org.knime.base.node.preproc.append.row.AppendedRowsNodeFactory`
- `org.knime.base.node.io.filehandling.linereader.LineReaderNodeFactory`

**Comment by qqilihq** [comment]
All fixed.
